// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package location

import (
	"net/http"

	"github.com/Nurlan270/weather-go/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocationRepository creates a new instance of MockLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepository {
	mock := &MockLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocationRepository is an autogenerated mock type for the LocationRepository type
type MockLocationRepository struct {
	mock.Mock
}

type MockLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepository) EXPECT() *MockLocationRepository_Expecter {
	return &MockLocationRepository_Expecter{mock: &_m.Mock}
}

// CreateLocation provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) CreateLocation(userID int64, name string, lat float64, lon float64) error {
	ret := _mock.Called(userID, name, lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for CreateLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string, float64, float64) error); ok {
		r0 = returnFunc(userID, name, lat, lon)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocationRepository_CreateLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLocation'
type MockLocationRepository_CreateLocation_Call struct {
	*mock.Call
}

// CreateLocation is a helper method to define mock.On call
//   - userID int64
//   - name string
//   - lat float64
//   - lon float64
func (_e *MockLocationRepository_Expecter) CreateLocation(userID any, name any, lat any, lon any) *MockLocationRepository_CreateLocation_Call {
	return &MockLocationRepository_CreateLocation_Call{Call: _e.mock.On("CreateLocation", userID, name, lat, lon)}
}

func (_c *MockLocationRepository_CreateLocation_Call) Run(run func(userID int64, name string, lat float64, lon float64)) *MockLocationRepository_CreateLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLocationRepository_CreateLocation_Call) Return(err error) *MockLocationRepository_CreateLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocationRepository_CreateLocation_Call) RunAndReturn(run func(userID int64, name string, lat float64, lon float64) error) *MockLocationRepository_CreateLocation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLocation provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) DeleteLocation(id int64, userID int64) error {
	ret := _mock.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocationRepository_DeleteLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLocation'
type MockLocationRepository_DeleteLocation_Call struct {
	*mock.Call
}

// DeleteLocation is a helper method to define mock.On call
//   - id int64
//   - userID int64
func (_e *MockLocationRepository_Expecter) DeleteLocation(id any, userID any) *MockLocationRepository_DeleteLocation_Call {
	return &MockLocationRepository_DeleteLocation_Call{Call: _e.mock.On("DeleteLocation", id, userID)}
}

func (_c *MockLocationRepository_DeleteLocation_Call) Run(run func(id int64, userID int64)) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocationRepository_DeleteLocation_Call) Return(err error) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocationRepository_DeleteLocation_Call) RunAndReturn(run func(id int64, userID int64) error) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocationByID provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) GetLocationByID(id int64) (entity.Location, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLocationByID")
	}

	var r0 entity.Location
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (entity.Location, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) entity.Location); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(entity.Location)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationRepository_GetLocationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocationByID'
type MockLocationRepository_GetLocationByID_Call struct {
	*mock.Call
}

// GetLocationByID is a helper method to define mock.On call
//   - id int64
func (_e *MockLocationRepository_Expecter) GetLocationByID(id any) *MockLocationRepository_GetLocationByID_Call {
	return &MockLocationRepository_GetLocationByID_Call{Call: _e.mock.On("GetLocationByID", id)}
}

func (_c *MockLocationRepository_GetLocationByID_Call) Run(run func(id int64)) *MockLocationRepository_GetLocationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocationRepository_GetLocationByID_Call) Return(location entity.Location, err error) *MockLocationRepository_GetLocationByID_Call {
	_c.Call.Return(location, err)
	return _c
}

func (_c *MockLocationRepository_GetLocationByID_Call) RunAndReturn(run func(id int64) (entity.Location, error)) *MockLocationRepository_GetLocationByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListLocationIdsByUserID provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) ListLocationIdsByUserID(userID int64) ([]int64, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListLocationIdsByUserID")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]int64, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []int64); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationRepository_ListLocationIdsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLocationIdsByUserID'
type MockLocationRepository_ListLocationIdsByUserID_Call struct {
	*mock.Call
}

// ListLocationIdsByUserID is a helper method to define mock.On call
//   - userID int64
func (_e *MockLocationRepository_Expecter) ListLocationIdsByUserID(userID any) *MockLocationRepository_ListLocationIdsByUserID_Call {
	return &MockLocationRepository_ListLocationIdsByUserID_Call{Call: _e.mock.On("ListLocationIdsByUserID", userID)}
}

func (_c *MockLocationRepository_ListLocationIdsByUserID_Call) Run(run func(userID int64)) *MockLocationRepository_ListLocationIdsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocationRepository_ListLocationIdsByUserID_Call) Return(int64s []int64, err error) *MockLocationRepository_ListLocationIdsByUserID_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockLocationRepository_ListLocationIdsByUserID_Call) RunAndReturn(run func(userID int64) ([]int64, error)) *MockLocationRepository_ListLocationIdsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationClient creates a new instance of MockLocationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationClient {
	mock := &MockLocationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocationClient is an autogenerated mock type for the LocationClient type
type MockLocationClient struct {
	mock.Mock
}

type MockLocationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationClient) EXPECT() *MockLocationClient_Expecter {
	return &MockLocationClient_Expecter{mock: &_m.Mock}
}

// GetCitiesInfo provides a mock function for the type MockLocationClient
func (_mock *MockLocationClient) GetCitiesInfo(cityName string) (*http.Response, error) {
	ret := _mock.Called(cityName)

	if len(ret) == 0 {
		panic("no return value specified for GetCitiesInfo")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return returnFunc(cityName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = returnFunc(cityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cityName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationClient_GetCitiesInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCitiesInfo'
type MockLocationClient_GetCitiesInfo_Call struct {
	*mock.Call
}

// GetCitiesInfo is a helper method to define mock.On call
//   - cityName string
func (_e *MockLocationClient_Expecter) GetCitiesInfo(cityName any) *MockLocationClient_GetCitiesInfo_Call {
	return &MockLocationClient_GetCitiesInfo_Call{Call: _e.mock.On("GetCitiesInfo", cityName)}
}

func (_c *MockLocationClient_GetCitiesInfo_Call) Run(run func(cityName string)) *MockLocationClient_GetCitiesInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocationClient_GetCitiesInfo_Call) Return(response *http.Response, err error) *MockLocationClient_GetCitiesInfo_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockLocationClient_GetCitiesInfo_Call) RunAndReturn(run func(cityName string) (*http.Response, error)) *MockLocationClient_GetCitiesInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetCityWeather provides a mock function for the type MockLocationClient
func (_mock *MockLocationClient) GetCityWeather(lat string, lon string) (*http.Response, error) {
	ret := _mock.Called(lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for GetCityWeather")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*http.Response, error)); ok {
		return returnFunc(lat, lon)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *http.Response); ok {
		r0 = returnFunc(lat, lon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(lat, lon)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationClient_GetCityWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCityWeather'
type MockLocationClient_GetCityWeather_Call struct {
	*mock.Call
}

// GetCityWeather is a helper method to define mock.On call
//   - lat string
//   - lon string
func (_e *MockLocationClient_Expecter) GetCityWeather(lat any, lon any) *MockLocationClient_GetCityWeather_Call {
	return &MockLocationClient_GetCityWeather_Call{Call: _e.mock.On("GetCityWeather", lat, lon)}
}

func (_c *MockLocationClient_GetCityWeather_Call) Run(run func(lat string, lon string)) *MockLocationClient_GetCityWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocationClient_GetCityWeather_Call) Return(response *http.Response, err error) *MockLocationClient_GetCityWeather_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockLocationClient_GetCityWeather_Call) RunAndReturn(run func(lat string, lon string) (*http.Response, error)) *MockLocationClient_GetCityWeather_Call {
	_c.Call.Return(run)
	return _c
}
