// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"time"

	"github.com/Nurlan270/weather-go/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateSession(uuid string, userID int64, expiresAt time.Time) (*entity.Session, error) {
	ret := _mock.Called(uuid, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, time.Time) (*entity.Session, error)); ok {
		return returnFunc(uuid, userID, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int64, time.Time) *entity.Session); ok {
		r0 = returnFunc(uuid, userID, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int64, time.Time) error); ok {
		r1 = returnFunc(uuid, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockUserRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - uuid string
//   - userID int64
//   - expiresAt time.Time
func (_e *MockUserRepository_Expecter) CreateSession(uuid any, userID any, expiresAt any) *MockUserRepository_CreateSession_Call {
	return &MockUserRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", uuid, userID, expiresAt)}
}

func (_c *MockUserRepository_CreateSession_Call) Run(run func(uuid string, userID int64, expiresAt time.Time)) *MockUserRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateSession_Call) Return(session *entity.Session, err error) *MockUserRepository_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUserRepository_CreateSession_Call) RunAndReturn(run func(uuid string, userID int64, expiresAt time.Time) (*entity.Session, error)) *MockUserRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUser(login string, password string) (*entity.User, error) {
	ret := _mock.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*entity.User, error)); ok {
		return returnFunc(login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *entity.User); ok {
		r0 = returnFunc(login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - login string
//   - password string
func (_e *MockUserRepository_Expecter) CreateUser(login any, password any) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", login, password)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(login string, password string)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(user *entity.User, err error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(login string, password string) (*entity.User, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByLogin(login string) (*entity.User, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserRepository_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - login string
func (_e *MockUserRepository_Expecter) GetUserByLogin(login any) *MockUserRepository_GetUserByLogin_Call {
	return &MockUserRepository_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", login)}
}

func (_c *MockUserRepository_GetUserByLogin_Call) Run(run func(login string)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) Return(user *entity.User, err error) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) RunAndReturn(run func(login string) (*entity.User, error)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBySID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserBySID(sid string) (*entity.User, error) {
	ret := _mock.Called(sid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBySID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return returnFunc(sid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = returnFunc(sid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserBySID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySID'
type MockUserRepository_GetUserBySID_Call struct {
	*mock.Call
}

// GetUserBySID is a helper method to define mock.On call
//   - sid string
func (_e *MockUserRepository_Expecter) GetUserBySID(sid any) *MockUserRepository_GetUserBySID_Call {
	return &MockUserRepository_GetUserBySID_Call{Call: _e.mock.On("GetUserBySID", sid)}
}

func (_c *MockUserRepository_GetUserBySID_Call) Run(run func(sid string)) *MockUserRepository_GetUserBySID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserBySID_Call) Return(user *entity.User, err error) *MockUserRepository_GetUserBySID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserBySID_Call) RunAndReturn(run func(sid string) (*entity.User, error)) *MockUserRepository_GetUserBySID_Call {
	_c.Call.Return(run)
	return _c
}
